language: haskell
env:
  - 'UBUNTU_RELEASE=saucy GHCVER=7.6.1'
  - 'UBUNTU_RELEASE=saucy GHCVER=7.6.2'
  - 'UBUNTU_RELEASE=saucy GHCVER=7.6.3'

before_install:
  - 'sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu/ ${UBUNTU_RELEASE} main universe"'
  - 'sudo add-apt-repository -y ppa:hvr/ghc'
  - 'sudo apt-get update'
  - 'sudo apt-get install librados-dev'
  - 'sudo apt-get install cabal-install-1.18 ghc-$GHCVER happy'
  - 'export PATH=/opt/ghc/$GHCVER/bin:$PATH'
  - sudo apt-get remove libzmq1
  - wget http://download.zeromq.org/zeromq-4.0.4.tar.gz
  - tar -xf zeromq-4.0.4.tar.gz
  - cd zeromq-4.0.4
  - ./configure 
  - make
  - sudo make install
  - sudo su -c "echo '/usr/local/lib' > /etc/ld.so.conf.d/local.conf"
  - sudo ldconfig
  - cd ..

install:
  - 'cabal-1.18 update'
  - 'cabal-1.18 install --only-dependencies --enable-tests --enable-benchmarks'

script:
  - 'cabal-1.18 configure'
  - 'cabal-1.18 build'
  - 'cabal-1.18 sdist'
